;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        company-indent-or-complete-common
        forward-sexp
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        mouse-buffer-menu
        skeleton-pair-insert-maybe
        smart-comment
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        my-previous-buffer
        next-buffer
        previous-buffer
        ))
