;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        company-indent-or-complete-common
        hungry-delete-backward
        hungry-delete-forward
        mouse-buffer-menu
        skeleton-pair-insert-maybe
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        my-previous-buffer
        ))
